name: Grayscale Image Hover
author: realityking
current: 1.1
category: Effects
demo: http://realityking.github.com/grayscale-image-hover/
tags: [fx, grayscale, image]
copyright: "&copy; 2011 Rouven Weßling"
license: MIT
